apiVersion: v1
kind: Pod
metadata:
    name: flask-pod
    labels:
      name: flask_app
spec:
  containers:
    - image: "flask_image:v9"
      name: flask-container
      resources:
        limits:
          memory: 200Mi
          cpu: "1"
      ports:
        - containerPort: 1532