apiVersion: v1
kind: Pod
metadata:
   name: test-pod
spec: 
  containers: 
    - image: "nginx_test99:v1"
      name: test-container01
      resources:
        limits:
          memory: 200Mi
          cpu: "1"